### ISSUE TITLE
nltk.translate.metrics can't find edit_distance 

### ISSUE THREAD

**Issue by ricardorei** [Unbabel/smaug#53]
when running SMAUG with the following config:

```
pipeline:
- cmd: io-read-lines
  path: /home/ubuntu/smaug/smaug-test-zhen-news.txt
  lang: en
- cmd: transf-swp-ne
- cmd: transf-swp-num
- cmd: transf-neg
  validations:
  - cmd: val-keep-contradiction
- cmd: transf-swp-poisson-span
  validations:
    - cmd: val-keep-geq-edit-dist
      distance: 8
      level: word
- cmd: transf-ins-text
  validations:
  - cmd: val-keep-geq-edit-dist
    distance: 8
    level: word
- cmd: io-write-json
  path: /home/ubuntu/smaug/smaug-test-zhen-news.json
# Remove this line for no seed
seed: 12
```

I run into the following error:

AttributeError: module 'nltk.translate.metrics' has no attribute 'edit_distance'

I am using the latest nltk version (3.8.1)
