### ISSUE TITLE
cli command to read config

### ISSUE THREAD

**Issue by DuarteMRAlves** [Unbabel/smaug#7]
### Description
* Command to read a configuration file and execute the pipeline.
* The command should read a yaml file with the following format:
```yaml
transforms:
- <transform 1 name>:
  args (...)
  validations:
  - <specific validation 1 name>:
    args (...)
- <transform 2 name>:
  args (...)
validations:
- <validation 1 name>:
  args (...)
- <validation 2 name>:
  args (...)
<other options such as seed>
```
